// src/pages/Setting/Profile.tsx
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  Alert,
} from 'react-native';
import { Avatar } from '@tencentcloud/chat-uikit-react-native';
import { useUserStore } from '../../hooks/useUserStore';
import { BackHeader } from '../../components/BackHeader';

interface ProfileProps {
  navigation: any;
}

export const Profile: React.FC<ProfileProps> = ({ navigation }) => {
  const { user } = useUserStore();

  // 隐藏手机号中间四位
  const maskedPhone = user?.phone ? user.phone.replace(
    /(\d{3})\d{4}(\d{4})/,
    '$1****$2',
  ) : '未设置';

  const handleCopy = async () => {
    try {
      // 这里使用React Native的Clipboard
      console.log('复制用户ID:', user?.userId);
      Alert.alert('提示', '用户ID已复制到剪贴板');
    } catch (error) {
      Alert.alert('错误', '复制失败');
    }
  };

  const handleToNickname = () => {
    navigation.navigate('Nickname');
  };

  const handleToAvatar = () => {
    navigation.navigate('Avatar');
  };

  const handleToQRCode = () => {
    navigation.navigate('QRCode');
  };

  const handleToDeactivateUser = () => {
    navigation.navigate('DeactivateUser');
  };

  const profileItems = [
    {
      title: '账号',
      value: maskedPhone,
      onPress: () => Alert.alert('账号信息', `当前账号：${maskedPhone}`),
    },
    {
      title: '昵称',
      value: user?.nickname || '用户',
      onPress: handleToNickname,
    },
    {
      title: '头像',
      value: '',
      onPress: handleToAvatar,
      showAvatar: true,
    },
    {
      title: '用户ID',
      value: user?.userId || '1962350063745744898',
      onPress: handleCopy,
    },
    {
      title: '二维码名片',
      value: '',
      onPress: handleToQRCode,
    },
    {
      title: '账号注销',
      value: '',
      onPress: handleToDeactivateUser,
    },
  ];

  return (
    <SafeAreaView style={styles.container}>
      <BackHeader title="个人资料" />

      {/* Content */}
      <View style={styles.content}>
        {profileItems.map((item, index) => (
          <TouchableOpacity
            key={index}
            style={styles.profileItem}
            onPress={item.onPress}
          >
            <Text style={styles.profileTitle}>{item.title}</Text>
            <View style={styles.profileRight}>
              {item.showAvatar ? (
                <Avatar size={30} radius={15} uri={user?.avatarUrl || ''} />
              ) : (
                <Text style={styles.profileValue}>{item.value}</Text>
              )}
              <Text style={styles.arrow}>›</Text>
            </View>
          </TouchableOpacity>
        ))}
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  profileItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F0F0F0',
  },
  profileTitle: {
    fontSize: 16,
    color: '#333333',
  },
  profileRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileValue: {
    fontSize: 16,
    color: '#666666',
    marginRight: 8,
  },
  arrow: {
    fontSize: 18,
    color: '#CCCCCC',
  },
});

export default Profile;

// App/src/pages/Setting/packages-me/pages/mine/profile.vue
<template>
  <view class="profile">
    <uni-list>
      <uni-list-item showArrow title="账号" :rightText="maskedPhone" />
      <uni-list-item
        showArrow
        title="昵称"
        clickable
        :rightText="useUserStore.user.nickname"
        @click="handleToNickname"
      />
      <uni-list-item showArrow clickable @click="handleToAvatar" title="头像">
        <template #footer>
          <Avatar
            useSkeletonAnimation
            :url="useUserStore.user.avatarUrl"
            size="30px"
          />
        </template>
      </uni-list-item>
      <uni-list-item
        showArrow
        title="用户ID"
        :rightText="useUserStore.user.userId"
        clickable
        @click="handleCopy"
      />
      <uni-list-item
        showArrow
        title="二维码名片"
        clickable
        @click="handleToQRCode"
      />
      <uni-list-item
        showArrow
        title="账号注销"
        clickable
        @click="handleToDeactivateUser"
      />
    </uni-list>
  </view>
</template>

<script setup lang="ts">
import { computed } from "@/TUIKit/adapter-vue";
import { useUserStore } from "@/hooks/useUserStore";
import { appLinks } from "@/navigate";
import { ux } from "@/utils";
import Avatar from "@/TUIKit/components/common/Avatar/index.vue";

// 隐藏手机号中间四位
const maskedPhone = computed(() => {
  const phone = useUserStore.user?.phone;
  if (!phone) return "";
  const phoneStr = String(phone);
  return phoneStr.replace(/(\d{3})\d{4}(\d{4})/, "$1****$2");
});

const handleCopy = async (key: string) => {
  await uni.setClipboardData({ data: useUserStore.user?.userId ?? "" });
  ux.tips("复制成功");
};

const handleToNickname = () => {
  appLinks.nickname.navigate({});
};

const handleToAvatar = () => {
  appLinks.avatar.navigate({});
};

const handleToQRCode = () => {
  appLinks.qrCode.navigate({});
};

const handleToDeactivateUser = () => {
  appLinks.deactivateUser.navigate({});
};
</script>

<style lang="scss" scoped>
.avatar-item {
  display: flex;
  flex: 1;
  justify-content: space-between;
  align-items: center;
}
</style>

<style lang="scss">
.profile {
  .uni-list-item__content {
    justify-content: center;
  }
}
</style>
